print("Welcome to the calculator!")
print("I want you to enter 2 different numbers!")
number1 = int(input("Enter the first number: "))
number2 = int(input("Enter the second number: "))
print("You entered", number1, "and", number2)
print(number1, "+", number2, "=", number1 + number2)
print(number1, "-", number2, "=", number1 - number2)
print(number1, "*", number2, "=", number1 * number2)
print(number1, "/", number2, "=", number1 / number2)
print("Thank you for using the calculator!")
print("Have a nice day!")